- library/kubevirt_vmrs.py
- tests/vmrs.yml
* Added cloudinit parameter to the DOC section.
* Added cloudinit parameter to module argument spec as non-required.
* Added base64 import required to encode cloud-init data.
Fixes #36
> rfe: add cloud-init parameter to kubevirt_vmrs

- README.md
- lib/ansible/modules/cloud/kubevirt/kubevirt_ovm_status.py
- tests/kubevirt_ovm_stopped.yml
- tests/units/modules/test_kubevirt_ovm_status.py
* Rather basic, using name, namespace and state, sets the OVM running
attribute to either true or false.
* Add example playbook setting the baldr ovm to be stopped.
It uses Kubernetes Python client because of [this issue](https://github.com/kubevirt/client-python/issues/20) in KubeVirt python client, when clarified and/or fixed, the module should be modified to use KubeVirt's.
> feat: add module to start/stop an OVM

- .travis.yml
* With this change, once a tag is pushed, Travis should run the tests
and notify Ansible Galaxy to import the modules.
* Remove *before_install* as nothing from apt is actually used.
> make travis to build and publish to Galaxy on tags

- .travis.yml
* Without including master on the branches list, PRs are not tested.
* Fixes #63.
> travis: revert #59

- lib/ansible/module_utils/k8svirt/facts.py
- lib/ansible/module_utils/k8svirt/helper.py
- lib/ansible/module_utils/k8svirt/raw.py
- lib/ansible/modules/cloud/kubevirt/kubevirt_facts.py
- lib/ansible/modules/cloud/kubevirt/kubevirt_raw.py
- lib/ansible/modules/cloud/kubevirt/kubevirt_scale_vmirs.py
- lib/ansible/modules/cloud/kubevirt/kubevirt_vm_status.py
- tests/units/module_utils/k8svirt/test_k8svirt_raw.py
* Reorg arg_spec dicts to make them more flexible.
* Make sure `argspec` property uses the right dicts.
* Add documentation to facts module.
* Add documentation to `kubevirt_raw` module.
* Return block for `kubevirt_raw`.
* Return block for `kubevirt_scale_vmirs`.
* Return block for `kubevirt_vm_status`.
Fixes #70
> Add module documentation and return blocks.

- tests/playbooks/kubevirt_vm_facts.yml
The 'kind' parameter is mandatory for the task to identify which entity is being queried.
> Add kind for task

- lib/ansible/module_utils/k8svirt/helper.py
`client-python` expects `field_selector` and not `field_selectors`
https://github.com/kubevirt/client-python/blob/master/kubevirt/apis/default_api.py#L2913
fixes: #83
> Corrected kwargs to align with client-python

- requirements-dev.txt
Update requirements to use client-python release tag v0.1.0
fixes: #85 
Signed-off-by: Vatsal Parekh <vatsalparekh@outlook.com>
> Update requirements to use client-python release tag v0.1.0

- lib/ansible/modules/clustering/kubevirt/kubevirt_raw.py
The module was using the upstream k8s class by accident.
> Actually utilize KubeVirtVM class

- tests/units/modules/clustering/kubevirt/test_kubevirt_raw.py
I've finally figured out how to get the new dyn client tested properly. As usual the end result looks somewhat trivial and does not at all indicate the amount of head scratching and dead ends that went into its creation. But that's likely a good sign – if the solution seems simple, that's a good indication that it's the right one.
Please don't merge this PR, it's just for getting early comments. Come Monday I'll add the missing tests (and there were a few in the pre–dyn client code) and likely generalize the code a bit while I'm at it. Then I'll send the final PR with all the tests for this class.
> Re-add KubeVirtVM() tests with dynamic client

- lib/ansible/modules/clustering/kubevirt/kubevirt_raw.py
- tests/playbooks/e2e.yaml
- tests/playbooks/kubevirt_raw_pvc.yml
Commit 1: Bring back 'timeout' variable instead of 'wait_timeout'
Two options:
1. Switch to the new name – 'wait_timeout' – but then I need to modify existing playbooks to use the new var name.
2. Bring back the old var name, which is what this commit does.
I assume @machacekondra had a reason to switch to wait_timeout and it does sound cleaner. So, what do we do?
> Use 'wait_timeout' instead of 'wait' arg

- lib/ansible/modules/clustering/kubevirt/kubevirt_raw.py
For KubeVirtVM() to handle updating existing objects, merge_type must be properly handled. It wasn't before.
> Handle 'merge_type' var as required

- tests/playbooks/kubevirt_facts_vmipreset.yml
- tests/playbooks/kubevirt_raw_remove.yml
- tests/playbooks/kubevirt_raw_vmi_from_preset.yml
- tests/playbooks/kubevirt_raw_vmipreset.yml
The idea is that kubevirt_raw_vmi.yml and kubevirt_raw_vmi_from_preset.yml create 1:1 same VMIs, they just do it slightly differently.
> Clean up VMIPreset sample playbooks

- README.md
- lib/ansible/modules/clustering/kubevirt/kubevirt_vm.py
This PR is work in progress, and kind of propsal of simplyfing design to the `kubevirt_vm` module.
Currently only `memory`, `disks` and `volumes` are simplified. to be first level instead of nested. As per current implementeation I would keep the same interface of API as kubevirt is using so we will keep the diff/dry mode functionality of k8s module.
Also I propse to have just single module `kubevirt_vm` instead of two `kubevirt_raw` and `kubevirt_vm_status`. Feel free to comment.
```yaml
- name: Create VM
kubevirt_vm:
state: present
name: testvm
namespace: default
memory: 64M
disks:
- name: registrydisk
volumeName: registryvolume
disk:
bus: virtio
- name: cloudinitdisk
volumeName: cloudinitvolume
disk:
bus: virtio
volumes:
- name: registryvolume
registryDisk:
image: …
```
> Add kubevirt_vm module

- tests/playbooks/k8s_service.yml
One example should be enough – it's just to show that there are no differences between VMIs and standard container pods.
> Add sample playbook with a simple service definition

- lib/ansible/modules/clustering/kubevirt/kubevirt_vm.py
- tests/units/modules/clustering/kubevirt/test_kubevirt_vm.py
This patch fixes the `merge_dics` method. Previously it didn't work with nested dictionaries. For example merging dictinaries like:
```
dict1 = {
'labels': {'label1': 'value'}
}
dict2 = {
'labels': {'label2': 'value'}
}
```
Ended as `  'labels': {'label1': 'value'}` instead of `  'labels': {'label1': 'value', 'label2': 'value'}`.
This patch fixes it.
> Improve merge dict so it works with nested dict

- lib/ansible/modules/clustering/kubevirt/k8s_service.py
- tests/playbooks/k8s_service.yml
Let's make sure we're on the same page wrt to config parameters early. @machacekondra @pkliczewski 
The idea behind `spec` is:
1. One can completely ignore the module's parameters and provide the whole Service spec inline.
2. Any parameter not covered directly by the module for whatever reason can always be provided this way.
> Add a dedicated module for managing Services

- .gitignore
- lib/ansible/modules/clustering/kubevirt/kubevirt_vm.py
- tests/playbooks/kubevirt_vm_multus.yml
- tests/units/modules/clustering/kubevirt/test_kubevirt_vm.py
This PR propose structure to `interfaces` and `networks` parameters. I think the best solution would be to just pass it to kubevirt API again, but just flatten the structure. I was thinking even about doc, and again I propose just adding a link to official doc + some light doc of the parameter, and add example.
> kubvirt_vm: Add support for networks & interfaces

- lib/ansible/modules/clustering/kubevirt/kubevirt_rs.py
- lib/ansible/modules/clustering/kubevirt/kubevirt_vm.py
- tests/playbooks/k8s_template.yml
- tests/playbooks/k8s_vm.yml
- tests/playbooks/k8s_vmi.yml
- tests/playbooks/k8s_vmi_from_preset.yml
- tests/playbooks/k8s_vmirs.yml
- tests/playbooks/kind_crud.yml
- tests/playbooks/kubevirt_vm_multus.yml
According to [[1]], [[2]], `registryDisk` has been renamed to `containerDisk`, which has also been merged into kubevirt master branch.  So this pull request is to be in line with the upstream change and includes the following changes:
1. Rename `registryDisk` to `containerDisk` in XML declarations and documentations
2. Rename `registerdisk` to `containerdisk` in `disk.name` XML definitions and documentations
3. Use the new image `kubevirt/cirros-container-disk-demo:latest` instead of `kubevirt/cirros-registry-disk-demo:latest` in XML definitions and documentations
4. Use the new image `kubevirt/fedora-cloud-container-disk-demo:latest` instead of `kubevirt/fedora-cloud-registry-disk-demo:latest` in XML definitions and documentations
5. Add new `path` support for `containerDisk` declaration …
> Rename registryDisk to containerDisk

- tests/playbooks/e2e.yaml
- tests/playbooks/k8s_pvc.yml
CDI is not guaranteed to immediately annotate a PVC it detects. And if a
task assumes the annotation is there before it's there, the whole
playbook fails with an error like so:
"The conditional check 'pvc.resources[0].status.phase == 'Bound' and pvc.resources[0].metadata.annotations['cdi.kubevirt.io/storage.pod.phase'] == 'Running'' failed. The error was: error while evaluating conditional (pvc.resources[0].status.phase == 'Bound' and pvc.resources[0].metadata.annotations['cdi.kubevirt.io/storage.pod.phase'] == 'Running'): 'dict object' has no attribute 'cdi.kubevirt.io/storage.pod.phase'"
> playbooks: fix race in waiting-for-CDI tasks

- lib/ansible/module_utils/kubevirt.py
- lib/ansible/modules/clustering/kubevirt/kubevirt_preset.py
- lib/ansible/modules/clustering/kubevirt/kubevirt_rs.py
- lib/ansible/modules/clustering/kubevirt/kubevirt_vm.py
- tests/units/modules/clustering/kubevirt/test_kubevirt_preset.py
- tests/units/modules/clustering/kubevirt/test_kubevirt_scale_rs.py
- tests/units/modules/clustering/kubevirt/test_kubevirt_vm.py
Use underlying library to dynamically discover supported api version for the k8s objects we operate on. Make sure to do something user–friendly in all possible cases, including "cluster too new to handle" and "cluster really old, but we can manage".
Fixes #77
> Add api version detection logic

- requirements-dev.txt
I've seen the changes in 0.9. Our code won't work with that version without some serious changes.
> Limit reqs to openshift client <0.9.0

- lib/ansible/module_utils/kubevirt.py
- tests/units/modules/clustering/kubevirt/test_kubevirt.py
Python3 vs. python2 incompatibilities made my last PR not work correctly on the latter. This should fix it.
> Make api detection logic python2 compatible

- tests/ansible.cfg
QE needs `ansible.cfg` to be the way it was until we actually merge the last module upstream and remove it from our repo. So a bit more time still.
> Revert "Update ansible.cfg"

- tests/playbooks/e2e.yaml
This change makes e2e playbook work in both dev and QE env
Correct storage class name
Fixes #
```release-note
correction in storage class name
```
> Update storageClassName to be used for QE env

- roles/app_deployment/README.md
- roles/app_deployment/defaults/main.yml
- roles/app_deployment/examples/network_policy.yml
- roles/app_deployment/tasks/main.yml
- roles/app_deployment/templates/network_policies.j2
- tests/roles/deploy.yml
Add new `kubevirt_app_network_policies` parameter to `app_deployment` role to manage Kubernetes `NetworkPolicy` object.
> Add network policy specification

- tests/playbooks/all.yml
- tests/playbooks/e2e.yaml
- tests/playbooks/known_issues.yaml
- tests/playbooks/known_issues/github.yaml
- tests/playbooks/kubevirt_dv_vm.yaml
- tests/playbooks/kubevirt_preset.yml
- tests/playbooks/kubevirt_pvc.yml
- tests/playbooks/kubevirt_vm.yml
- tests/playbooks/kubevirt_vmir.yml
The case detection logic can't be done globally in an easy manner, since there's no variable sharing between playbooks. So it's run for each playbook with known potential issues. Seems to work.
> Dynamic test skipping based on issues status

- roles/app_deployment/examples/deploy.yml
- tests/roles/deploy.yml
This PR fixes the affinity tests of related to app_deployment role. `topology_key` is required, so it must be passed in tests as well.
> Add topology_key to affinity tests and examples

- tests/playbooks/known_issues.yaml
Only 2.8.1 has it, 2.8.2 won't.
> stable-2.8 no longer has the pvc regression

- tests/playbooks/known_issues.yaml
- travis/print-debug-info.sh
- travis/run-cluster.sh
What this does: sleep for 90 seconds before running a new playbook if env == travis. This gives minikube time to recover after whatever's wrong with it and then correctly run the next playbook.
> Workaround for travis+minikube instability

- tests/playbooks/known_issues.yaml
- tests/playbooks/kubevirt_pvc.yml
Regarding pvc cloning – this used to be possible with CDI, but with 1.9.4 cloning got limited to datavols only and won't be reintroduced for PVCs. However in k8s 1.15 spec.dataSource got introduced and it does the same thing. So once kubevirt_pvc gets support for that, there should again be a test for it here.
> Drop pvc cloning and obsolete known issues

- .travis.yml
- jenkins/cluster-sync.sh
- travis/run-cluster.sh
Force previous CDI version for the time being. I'll add support for latest version in a separate patch.
> Stop CI complaining about latest CDI

- .travis.yml
Custom builds override env:, so builds can't depend on vars defined there to be present… so move them to script:
AKA make it easy to trigger custom builds against upstream ansible PRs.
> Travis: make sure required env vars are always being set

- .travis.yml
- jenkins/tests.bats
This should've been added three weeks ago.
> Add branch/stable-2.9 to CI tests
