library/kubevirt_vm.py, tests/vm_from_source.yml
- remove iscsi target code
- make simpler to use registry disk
- make name and namespace mandatory
=> kubevirt_vm enhancements

library/kubevirt_ovm.py
Fixes #12 
* replaced virtualmachines resource by offlinevirtualmachines
* replace vm variable by ovm
* use kubernetes.client.rest.ApiException instead of Exception
* other minor pep8 fixes
=> issue: offline vms fixes

library/kubevirt_ovm.py, library/kubevirt_vm.py, library/kubevirt_vmrs.py
=> Document modules according to Ansible requirements

library/kubevirt_ovm.py, library/kubevirt_vm.py, library/kubevirt_vmrs.py
* Added missing colons
* Fixed typo, requiredi -> required
* Rephrased requirements for consistency
=> issue: make ansible-doc happy again

library/kubevirt_vmrs.py
Fixes #5 
* Applied same logic to kubevirt_vmrs as the other modules have, name
and namespace are required and the module would fail if src file has
different or missing name/namespace.
This PR does nothing else on the code, @alexxa please take a look.
=> issue: required parameters

library/kubevirt_vm.py
This commit adds/changes:
* 80c line length when possible
* split main() into few less complex methods
* added docstrings
The idea is to stick to PEP8 where possible, as Ansible forces to have imports below documentation which goes against Python standards.
I've tested this commit with `tests/vm.yml` and seems to work properly. Will do more testing before requesting review.
First step for #21
=> refactor: kubevirt_vm for python coding style

library/kubevirt_ovm.py
* 80c line length when possible
* split main() into few less complex methods
* added docstrings
Offline VM module refactored for fixing #21, tested against `tests/ovm.yml`, still to come `kubevirt_vmrs`.
=> refactor: kubevirt_ovm for python coding style

library/kubevirt_vmrs.py
* 80c line length when possible
* split main() into few less complex methods
* added docstrings
* Fixed issue with disks[] as template doesn't have *dev* key but *bus*
instead
Last PR for #21
=> refactor: kubevirt_vmrs for python coding style

library/kubevirt_ovm.py, library/kubevirt_vm.py, library/kubevirt_vmrs.py
Added insecure parameter to allow skipping SSL certificate validation, fixes #20.
@alexxa the PR is ready for reviewing, thanks!
=> Allow insecure connections

library/kubevirt_ovm.py, library/kubevirt_vm.py, library/kubevirt_vmrs.py
* Set author to KubeVirt Team <@kubevirt> on all three modules.
Fixes #29
=> rfe: changed author

library/kubevirt_vm.py
* Removed both from module's documentation.
Fixes #18
=> issue: Removed cdrom and disk parameters

LICENSE, library/kubevirt_ovm.py, library/kubevirt_vm.py, library/kubevirt_vmrs.py, meta/main.yml
* Changed license to match the one in modules.
* Changed issue tracker.
* Changed author.
* Added tags.
Fixes #37
=> issue: Updated module metadata

library/kubevirt_ovm.py, library/kubevirt_vm.py, library/kubevirt_vmrs.py
* Now when state is absent, pvc is not required, same behaviour as
before hiding registrydisk.
* Also moved all logic, only needed when state is present, after the
right conditional.
Fixes #41
=> issue: made pvc not required

README.md, lib/ansible/modules/cloud/kubevirt/kubevirt_scale_vmrs.py, tests/kubevirt_scale_vmrs.yml, tests/units/modules/test_kubevirt_scale_vmrs.py
@alexxa this PR is code complete, once #52 is merged, I'll rebase, add some lines on the readme and re-push.
=> feat: Scale VirtualMachineReplicaSets

README.md, meta/main.yml
* Remove comments and unnecessary fields from metadata file.
* List all modules and their purpose on the contents section.
* Improve instructions, especially to use the modules from Ansible Galaxy.
@alexxa these changes are meant to help usage, especially from Ansible Galaxy, PTAL.
=> galaxy: prepare modules for Galaxy

tests/playbooks/kubevirt_raw_vmirs.yml
=> fix: state in kubevirt_raw_vmirs to present

lib/ansible/module_utils/k8svirt/common.py, lib/ansible/modules/cloud/kubevirt/kubevirt_facts.py, lib/ansible/modules/cloud/kubevirt/kubevirt_raw.py, lib/ansible/modules/cloud/kubevirt/kubevirt_scale_vmirs.py, lib/ansible/modules/cloud/kubevirt/kubevirt_vm_status.py, tests/playbooks/kubevirt_scale_vmirs.yml, tests/playbooks/kubevirt_vm_stopped.yml, tests/units/modules/test_kubevirt_scale_vmirs.py, tests/units/modules/test_kubevirt_vm_status.py
Connection details can now be read from k8s configuration or specified on the playbook.
=> Improve connection

lib/ansible/module_utils/k8svirt/common.py, lib/ansible/module_utils/k8svirt/facts.py, lib/ansible/module_utils/k8svirt/helper.py, lib/ansible/module_utils/k8svirt/raw.py, lib/ansible/modules/cloud/kubevirt/kubevirt_raw.py, tests/playbooks/kubevirt_all_pvcs_facts.yml, tests/playbooks/kubevirt_pvc_facts.yml, tests/playbooks/kubevirt_pvcs_facts.yml, tests/playbooks/kubevirt_raw_pvc.yml, tests/playbooks/kubevirt_raw_pvc_remove.yml, tests/units/module_utils/k8svirt/test_k8svirt_helper.py, tests/units/modules/test_kubevirt_raw.py
The PR adds support for PVC actions such as create, remove and receive
facts of the PVC.
This PR requires the k8s endpoint in order to perform PVC actions using
hte PVC resources.
Also, it introduces the ability to wait till the pvc creation is
completed.
=> Support Persistent Volume Claim actions

tests/playbooks/kubevirt_pvc_facts.yml, tests/playbooks/kubevirt_pvcs_facts.yml
The tasks refer to gathering PVC facts and the message should reflect that.
=> Fix task description

README.md
Include the note in README for `verify_ssl`
=> Updated README for verify_ssl in ansible.cfg

lib/ansible/modules/clustering/kubevirt/kubevirt_raw.py, lib/ansible/modules/clustering/kubevirt/kubevirt_scale_vmirs.py, lib/ansible/modules/clustering/kubevirt/kubevirt_vm_status.py
Make sure all the _read_stream() methods have the same basic structure.
=> Unify exception handling across modules

lib/ansible/modules/clustering/kubevirt/kubevirt_raw.py, tests/units/modules/clustering/kubevirt/test_kubevirt_raw.py
1. Enable it. Was ommited before.
2. Make sure return values are serializable, otherwise there are errors when jsonizing on module exit.
=> Fix wait codepath in KubeVirtVM and add tests for it

tests/playbooks/kubevirt_facts_vmipreset.yml, tests/playbooks/kubevirt_facts_vmirs.yml, tests/playbooks/kubevirt_scale_vmirs.yml
Those playbooks are useful for testing, but only if they operate
on the same resources.
=> Unify (some) resource names in sample playbooks

tests/units/modules/clustering/kubevirt/test_kubevirt_raw.py, tests/units/modules/clustering/kubevirt/test_kubevirt_scale_vmirs.py, tests/units/modules/clustering/kubevirt/utils.py
This puts us at 76% total test coverage according to pytest and thus completes the __improve unit tests__ task. I hope…
=> Expand test coverage for scaling module

tests/playbooks/e2e.yaml
**What this PR does / why we need it:**
This PR will update the e2e tests:
1. Restart the VM
2. Increase/Decrease the resources of VM
=> e2e test update

README.md
* Use __OpenShift__ Python client
* Fix the wrong link to KubeVirt Python SDK
Signed-off-by: imjoey <majunjiev@gmail.com>
=> readme: Minor fixes for typo and link

lib/ansible/modules/clustering/kubevirt/kubevirt_vm.py
Signed-off-by: Ondra Machacek <omachace@redhat.com>
=> Simplify volumes & disks

tests/playbooks/kubevirt_vm_multus.yml
Fixes #154 
```release-note
NONE
```
=> Fixed: an example for NetworkAttachmentDefinition

lib/ansible/modules/clustering/kubevirt/kubevirt_vm.py, tests/playbooks/kubevirt_vm_multus.yml
Fixes #157
```release-note
```
=> Don't use volumes in kubevirt_vm

tests/playbooks/kubevirt_vm_multus.yml
=> Document proper cniVersion to use with multus

lib/ansible/modules/clustering/kubevirt/k8s_service.py
With minor workaround for supporting ansible <2.8.
Upstream PR: https://github.com/ansible/ansible/pull/48872
=> k8s_service: sync code with upstream PR

lib/ansible/modules/clustering/kubevirt/k8s_service.py
This might fix the ansible issue seen in the test env. @vatsalparekh please verify.
=> k8s_service: compat fix for older ansible

lib/ansible/modules/clustering/kubevirt/k8s_service.py, lib/ansible/modules/clustering/kubevirt/kubevirt_preset.py, lib/ansible/modules/clustering/kubevirt/kubevirt_rs.py, lib/ansible/modules/clustering/kubevirt/kubevirt_vm.py, lib/ansible/utils/module_docs_fragments/kubevirt_common_options.py, requirements-dev.txt
Needed for CDI upload to work correctly.
@machacekondra or @pkliczewski plz merge, so QA can check cdi uploading.
=> Bump min openshift rest client lib ver

lib/ansible/module_utils/kubevirt.py
=> Make kubevirt modules work with api v1alpha3

lib/ansible/modules/clustering/kubevirt/k8s_auth.py, tests/playbooks/k8s_auth.yml
Upstream PR: https://github.com/ansible/ansible/pull/50807
**What this PR does / why we need it**: makes ansible/k8s usable with openshift auth
Fixes #151 
**Special notes for your reviewer**: don't tell the other reviewers, but you're my favorite reviewer.
=> Add k8s_auth from upstream PR

.gitignore
Added ansible.log to gitignore
Just merge it
```release-note
Added ansible.log to gitignore
```
=> Added ansible.log to gitignore

tests/playbooks/e2e.yaml
Fixed e2e playbook
```release-note
Fixed e2e playbook with updated modules
```
=> Fixed e2e playbook

lib/ansible/module_utils/kubevirt.py, lib/ansible/modules/clustering/kubevirt/kubevirt_preset.py, lib/ansible/modules/clustering/kubevirt/kubevirt_rs.py, lib/ansible/modules/clustering/kubevirt/kubevirt_template.py, lib/ansible/modules/clustering/kubevirt/kubevirt_vm.py
This PR add new kubevirt_template module.
Fixes #
```release-note
```
=> Add template module

lib/ansible/module_utils/kubevirt.py, lib/ansible/modules/clustering/kubevirt/kubevirt_vm.py, lib/ansible/utils/module_docs_fragments/kubevirt_common_options.py, tests/playbooks/e2e.yaml
=> Add cpu_cores parameter

lib/ansible/module_utils/kubevirt.py, lib/ansible/modules/clustering/kubevirt/kubevirt_vm.py
=> Fix cloud-init to work with version v1alpha3

lib/ansible/module_utils/kubevirt.py
=> Fix disk and volumes creation

lib/ansible/module_utils/kubevirt.py
=> Fix interfaces and networks creation

tests/playbooks/k8s_facts_vm.yml, tests/playbooks/kubevirt_preset.yml
=> Small tests fixes

.gitmodules, .travis.yml, test.sh, tests/playbooks/e2e.yaml
This PR add e2e test to be executed per each PR on travis on Minikube
=> Add e2e test to be executed per each new PR

.travis.yml, test.sh
=> Fix execute unit tests before integration test

tests/playbooks/e2e.yaml
Reduce disk and memory to make tests faster and smaller, to also help travis
```release-note
Reduce disk and memory size
```
=> Reduce the disk and memory size for e2e

tests/playbooks/k8s_auth.yml
No more clunky yaml anchors, yay!
=> Switch k8s_auth.yml to using module defaults

README.md, tests/playbooks/kubevirt_pvc_img_upload.yml
This requires some background info to operate properly. (At least until the module gets autodetection code merged.)
=> Info on using kubevirt_cdi_upload module

tests/playbooks/k8s_facts.yml, tests/playbooks/k8s_facts_vm.yml, tests/playbooks/k8s_facts_vmi.yml, tests/playbooks/k8s_facts_vmipreset.yml, tests/playbooks/k8s_facts_vmirs.yml, tests/playbooks/k8s_remove.yml, tests/playbooks/k8s_template.yml, tests/playbooks/k8s_vm.yml, tests/playbooks/k8s_vmi.yml, tests/playbooks/k8s_vmi_from_preset.yml, tests/playbooks/k8s_vmipreset.yml, tests/playbooks/k8s_vmirs.yml, tests/playbooks/kind_crud.yml
=> Update all kubevirt.io apivers to v1alpha3

tests/playbooks/k8s_template.yml, tests/playbooks/k8s_vm.yml, tests/playbooks/k8s_vmi.yml, tests/playbooks/k8s_vmi_from_preset.yml, tests/playbooks/k8s_vmirs.yml, tests/playbooks/kind_crud.yml
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1681888
=> Remove volumeName from tests

README.md
=> Add info how to use KubeVirt inv plugin

tests/playbooks/kubevirt_pvc.yml, tests/playbooks/kubevirt_pvc_img_upload.yml
Once https://github.com/ansible/ansible/pull/53692 gets merged, this should be as well.
=> Switch to 'wait: yes' for PVCs

tests/playbooks/e2e.yaml
Use the new module_defaults feature
Fixes #
```release-note
Use module_defaults feature
```
=> Use module_defaults feature

.travis.yml
Add PR_NUMBER env variable to build job so we can test unmerged PRs.
=> Add PR_NUMBER env var

tests/playbooks/e2e.yaml
=> Switch to 'wait: yes' for PVCs, part 2

tests/playbooks/kubevirt_pvc.yml
One feature was missing from the test.
=> Add pvc cloning to kubevirt_pvc.yml

.travis.yml
=> Send notification on faliure

tests/playbooks/all.yml, tests/playbooks/kubevirt_vm.yml
Make sure all the logic gets tested.
=> Add comprehensive kubevirt_vm testing

README.md
As soon as this is merged: https://github.com/ansible/ansible/pull/55903
Merge this one.
=> inv plugin: Rename network name to interface name

tests/playbooks/all.yml, tests/playbooks/kubevirt_dv_vm.yaml
Added example for VM with DataVolumes
Fixes #
```release-note
Added example for VM with DataVolumes
```
=> DataVolume example

tests/playbooks/kubevirt_dv_vm.yaml
Fixes #
```release-note
Fix the failing check
```
=> Fix the failing check

test.sh
=> Enabled Data volumes

tests/ansible.cfg, tests/playbooks/kubevirt_vm_multus.yml, tests/playbooks/plugin/kubevirt.yaml, tests/playbooks/plugin/touch-vmi.yaml
Fixes #
```release-note
Added example/test for Inventory plugin
```
=> Added example for Inventory plugin

tests/playbooks/e2e.yaml
Fixes #
```release-note
Changes for better automation tests
```
=> Changes for better automation tests

tests/playbooks/all.yml, tests/playbooks/kubevirt_template.yaml
Fixes #
```release-note
Added example for Templates and VM from templates
```
=> Added example for Templates and VM from templates

.gitignore, automation/check-patch.os-3.11.0.mounts, automation/check-patch.os-3.11.0.packages, automation/check-patch.os-3.11.0.sh, cluster/common.sh, cluster/sync.sh, cluster/up.sh
=> Add openshift3 jenkins target support

automation/test.sh, cluster/up.sh, tests/playbooks/all.yml
This will make it waay easier to figure out what's causing CI failures.
=> Better logging + test multiple ansible versions

roles/app_deployment/README.md, roles/app_deployment/examples/deploy.yml, roles/app_deployment/tasks/vms.yml, tests/roles/deploy.yml
Add affinity parameters to app_deployment role
Depends on: https://github.com/ansible/ansible/pull/57359
=> Add affinity parameters to app_deployment role

roles/vm_image/README.md, roles/vm_image/examples/example1.yml, roles/vm_image/examples/example2.yml, roles/vm_image/tasks/main.yml, roles/vm_image/tasks/pvc.yml, roles/vm_image/templates/cdi_source.j2
No tests, because:
1. Role tests aren't enabled.
2. And even if they were, #242 wouldn't let this role pass correctly anyway.
Maybe we can deal with enabling role tests as part of the "fix #242" story, next sprint? Or do I just plunk some test somewhere and we'll fix it later?
=> Add vm_image role

tests/playbooks/all.yml
Until we have separate jobs for devel and stable ansible.
=> Disable tests of known broken modules

roles/vm_image/tasks/pvc.yml
Minor issue I missed when adding the image upload task.
=> Fix upload task when source: not defined

.gitmodules, .travis.yml, tests/playbooks/known_issues.yaml, tests/playbooks/known_issues/github.yaml, travis/install-ansible.sh, travis/install-cluster.sh, travis/print-debug-info.sh, travis/run-cluster.sh
Travis is faster/more reliable than our Jenkins, if more limited in what it can do.
=> Bring back travis builds based on minikube

.travis.yml
I accidentally removed it at some point.
=> Travis: re–add role tests to the matrix

roles/app_deployment/README.md
Instead of the table, Markdown syntax is displayed. This PR fixes it. 
Fixes #
```release-note
NONE
```
=> Fix Markdown table syntax in Readme

roles/app_deployment/README.md
- fix parameters' names in Readme to match the source code. 
- replace a copy of the example playbook with a link to it, so it's easier to maintain if there are any changes. 
Fixes #
```release-note
NONE
```
=> Update Readme of app_deployment role

roles/app_deployment/examples/deploy.yml
=> Add cloud_init example for app_deploy role

roles/app_deployment/README.md, roles/app_deployment/tasks/vms.yml, tests/roles/deploy.yml
Adding WIP, because we need to first merge this:
https://github.com/ansible/ansible/pull/57223
=> Add hostname and subdomain to app_deployment role

roles/app_deployment/README.md
=> Update app_deployment role README.md

examples/blog/README.md, examples/blog/part1/01_vm1_running.yaml, examples/blog/part1/02_vm1.yaml, examples/blog/part1/03_vm1_absent.yaml
I've put them originally in my own repo, to make it easy to iterate for me, but long term they should be stored here.
=> Move blog post examples to this repo

examples/blog/part2/ansible.cfg, examples/blog/part2/kubevirt.yaml, examples/blog/part2/pvc.yaml, examples/blog/part2/pvc_cdi.yaml
Accompanies https://github.com/kubevirt/kubevirt.github.io/pull/283
=> Files for blog post part 2

.travis.yml
Fixes #
```release-note
Add more people to failure notification emails
```
=> Add more people to failure notification emails

.travis.yml
Signed-off-by: Tareq Alayan <talayan@redhat.com>
Fixes #
```release-note
```
=> unsubscribe myself from mailing list
